# Define product categories with their respective product names.
product_categories = {
    "Lifestyle": [
        "Curcumin Unlocked",
        "Fibre Feel",
        "Collagen Full Spectrum Powder",
        "L-Glycine Vegan Amino Acid",
        "5-HTP 100 with B6 & Magnesium",
        "Active Multi Drink Mix - Juicy Blueberry",
        "Adrenal Chill",
        "Adrenal Chill - Men",
        "Adrenal-Pro Recharge Yourself",
        "Adult Multi",
        "Alpha Lipoic Acid 600",
        "Antioxidant Network",
        "Ashwagandha Body & Mind",
        "B12 Methyl 500mcg Drops",
        "B9 Folate 200mcg Drops",
        "Beautiful Skin",
        "Berberine 500mg",
        "BioActive B",
        "BioActive B",
        "BioActive B - Liquid",
        "BioPQQ®",
        "Black Walnut Complex",
        "Blood Sugar Support",
        "Reishi Full Spectrum",
        "Resvera-Pro",
        "Rocket T Testosterone Recharge",
        "Selenium Glycinate 200",
        "Silicon + Biotin",
        "Silicon + Biotin Liquid",
        "Sleep-Reset Melatonin",
        "Sleep-Restore Ashwagandha",
        "Synergy B",
        "Synergy C",
        "Thyroid Plus",

    ],
    "Health Goals": [
        "Myco 10 Mushroom Complex",
        "K2Drops",
        "Myco-Inosital",
        "Green Up! with Grams",
        "Lipsomal Milk Thistle Coconut",
        "D3 & K2 Drops - MCT base",
        "D3 & K2 - Organic Coconut Oil",
        "D3 & K2 - Organic Coconut Oil",
        "D3 2500IU - MCT Base",
        "D3 2500IU - MCT Base",
        "D3 Drops 1000IU - MCT base",
        "D3 Drops 1000IU - Vegan",
        "D3 Drops 2500IU - MCT Base",
        "D3 Drops Kids 400IU - MCT base",
        "Detox-Pro Formula",
        "Digestive Enzymes",
        "Elderberry C Chewable - Berry Burst",
        "Elderberry C Liquid - Berry Burst",
        "ElectroMag Effervescent Drink - Box",
        "EliteNeuro",
        "Eye-Pro Formula",
        "Fibre Feel",
        "GABA 500",
        "GI-Pro Formula (formerly Digestion & IBS)",
        "Green Tea",
        "Green Up! with GRAMS",
        "Gut Repair",
        "Healthy Bones MCHA",
        "Healthy Bones MCHA",
        "Healthy Bones Vegan",
        "Healthy Bones Vegan",
        "Healthy Hair",
        "Healthy Heart",
        "Healthy Hormones",
        "Healthy Lungs",
        "Healthy Mood",
        "Heme Iron",
        "Hya Love - Hyaluronate for Hydration",
        "I-3-C 200",
        "Immuno Berry",
        "Immuno Multi",
        "Inno-Cal-Mag Advanced",
        "Inno-Cal-Mag Advanced",
        "Inno-Q-Nol® 100mg",
        "Inno-Q-Nol® 100mg",
        "Inno-Q-Nol® 100mg",
        "Inno-Q-Nol® 200mg",
        "Inno-Q-Nol® 200mg",
        "Iron Bis·Glycinate 20",
        "Iron Bis·Glycinate 20 - Liquid",
        "Iron Bis·Glycinate 25",
        "Joint-Pro Concentrate - Liquid",
        "Joint-Pro Formula",
        "Joint-Pro NEM",
        "K2",
        "K2 Drops",
        "Krill Oil",
        "Krill Oil",
        "L-Arginine Vegan Amino Acid",
        "L-Glutamine Vegan Amino Acid",
        "L-Glycine Vegan Amino Acid",
        "L-Lysine Vegan Amino Acid",
        "L-Taurine Vegan Amino Acid",
        "L-Theanine with Magnesium",
        "L-Tyrosine Vegan Amino Acid",
        "Lion's Mane Full Spectrum",
        "Liposomal Coenzyme Q10 75mg - Citrus",
        "Liposomal Curcumin 100 - Peach",
        "Liposomal GABA - Citrus",
        "Liposomal Glutathione",
        "Liposomal Magnesium - Nutty Chocolate Caramel",
        "Liposomal Melatonin - Nutty Chocolate",
        "Liposomal Milk Thistle - Coconut Caramel Nut",
        "Liposomal NAC - Strawberry",
        "Liposomal Quercetin - Pineapple",
        "Liposomal Vitamin C - Citrus Vanilla",
        "Liposomal Vitamin C 1000 - Citrus Vanilla",
        "Lutein 20  - Blue Light Defence",
        "Magnesium + Vegan D3 & K2",
        "Magnesium Bis·Glycinate 140 Extra Gentle",
        "Magnesium Bis·Glycinate 200 Gentle",
        "Magnesium Bis·Glycinate 200 Gentle Powder",
        "Magnesium Bis·Glycinate 300 Ultra Gentle - Juicy Blueberry",
        "Magnesium Bis·Glycinate 300 Ultra Gentle - Liquid",
        "Magnesium Bis·Glycinate 400 Ultra Gentle - Powder",
        "Magnesium Bis·Glycinate 50 Chewable - Tropical Pineapple",
        "Magnesium Bis·Glycinate 80 Ultra Gentle",
        "Magnesium Bis·Glycinate Drink Mix - Juicy Blueberry",
        "Magnesium Bis·Glycinate Drink Mix - Refreshing Orange Zest",
        "Magnesium Cardio + Taurine, B6 & Zinc",
        "Magnesium Citrate+",
        "Magnesium Full Spectrum",
        "Magnesium Malate",
        "Magnesium Multi Mineral",
        "Magnesium Sleep + GABA & Melatonin",
        "Magnesium Stress Release",
        "Magnesium Threonate",
    ],
    "Dietary Preferences": [
        "Collagen Beauty powder",
        "Lipsomal curcumin 100 Peach",
        "Magnesium Bis Blueberry",
        "Calcium Malate Bis·Glycinate 200",
        "Chaga Full Spectrum",
        "Choline 275mg",
        "Chromium Nicotinate Glycinate 200",
        "Cold-Pro Immune Formula",
        "Collagen Beauty - Liquid",
        "Collagen Beauty - Powder",
        "Collagen Bone - Powder",
        "Collagen Full Spectrum - Powder",
        "Collagen Full Spectrum Blend - Liquid",
        "Collagen Joint & Cartilage - Powder",
        "Collagen Tendo Recover - Powder",
        "Collagen Tone - Powder (formerly Collagen Muscle Tone)",
        "CoQ10 M.R.B. 100mg",
        "Cordyceps Full Spectrum",
        "Cramp Relief",
        "Curcumin Unlocked",
        "Curcumin-Pro",
        "D3 - Organic Coconut Oil",
        "D3 - Organic Coconut Oil",
        "D3 & K2 - Organic Coconut Oil",
        "L-Glutamine Vegan Amino Acid",
        "CP-Lipsomals-Quercetin",
        "Thyroid-Pro Formula",
        "TUDCA",
        "Turkey Tail Full Spectrum",
        "Type II Collagen",
        "Ubiquinol 100 with MCT Oil",
        "UTI Protect",
        "UV Skin Protect",
        "V Biotik Vaginal & UTI",
        "Vitamin A - Drops",
        "Vitamin C 1000mg",
        "Women's Multi",
        "Zinc 50 Ultra Immune + Vitamin C",
        "Zinc Bis·Glycinate 25",
        "Zinc Bis·Glycinate 50 Ultra Strength",
    ],
    "By Products": [
        "CP-ElectroMagEfferescentDrink",
        "Lipsomal Magnesium 50 Salted Caramel",
        "CP-ElderC Liquid",
        "CP-Post-BiotikImmuno Biotics",
        "CPB-Silicon Beauty Liquid",
        "Melatonin 3mg Sustained-Release",
        "Meno Chill",
        "Meno-Prev + Mood & Memory",
        "Mind-Pro Formula",
        "Multi-Mushroom Full Spectrum",
        "MuscleRescue - Fruit Punch",
        "MuscleRescue - Pineapple Punch",
        "Myco10 Immunomodulating Mushroom Complex",
        "Myo-Inositol",
        "NAC+ N-Acetyl-L-Cysteine",
        "Nattokinase",
        "Olive Leaf Extract",
        "Omega Twist - Peachy Mango",
        "Omega Twist - Tangerine Tang",
        "Omega-Pro Balance 1:1",
        "Omega-Pro Essential HP 40/20",
        "Omega-Pro High DHA",
        "Omega-Pro High EPA",
        "Oregano Oil",
        "Osteo Prolong",
        "Pain-Pro Formula",
        "PCOS-Pro Ultra Relief",
        "Post-Biotik Immunobiotics",
        "Prenatal Multi",
        "Prime Cycle  (formerly Prime Fertility)",
        "Prime Virility Fertility & Testosterone",
        "Pro-Biotik 15B",
        "Pro-Biotik 50B Extra Strength",
        "Pro-Biotik 50B Extra Strength",
        "Pro-Biotik IBS Support",
        "Prostate-Pro + Maca Support",
        "Pureway C 600mg",
        "Quercetin 500mg",
        "Red Yeast Rice Complex",
        "Red Yeast Rice Complex",
    ]
}

# product_images = {
#     "5-HTP 100 with B6 & Magnesium": "downloaded_images\\5-HTP 100 with B6 & "
#     "Magnesium.png",
#     "Active Multi Drink Mix - Juicy Blueberry": "downloaded_images\\Active Multi "
#     "Drink Mix - Juicy Blueberry.png",
#     "Adrenal Chill": "downloaded_images\\Adrenal Chill.png",
#     "Adrenal Chill - Men": "downloaded_images\\Adrenal Chill - Men.png",
#     "Adrenal-Pro Recharge Yourself": "downloaded_images\\Adrenal-Pro Recharge "
#     "Yourself.png",
#     "Adult Multi": "downloaded_images\\Adult Multi.png",
#     "Alpha Lipoic Acid 600": "downloaded_images\\Alpha Lipoic Acid 600.png",
#     "Antioxidant Network": "downloaded_images\\Antioxidant Network.png",
#     "Ashwagandha Body & Mind": "downloaded_images\\Ashwagandha Body & Mind.png",
#     "B12 Methyl 500mcg Drops": "downloaded_images\\B12 Methyl 500mcg Drops.png",
#     "B9 Folate 200mcg Drops": "downloaded_images\\B9 Folate 200mcg Drops.png",
#     "Beautiful Skin": "downloaded_images\\Beautiful Skin.png",
#     "Berberine 500mg": "downloaded_images\\Berberine 500mg.png",
#     "BioActive B": "downloaded_images\\BioActive B.png",
#     "BioActive B - Liquid": "downloaded_images\\BioActive B - Liquid.png",
#     "BioPQQ®": "downloaded_images\\BioPQQ®.png",
#     "Black Walnut Complex": "downloaded_images\\Black Walnut Complex.png",
#     "Blood Sugar Support": "downloaded_images\\Blood Sugar Support.png",
#     "Calcium Malate Bis·Glycinate 200": "downloaded_images\\Calcium Malate "
#     "Bis·Glycinate 200.png",
#     "Chaga Full Spectrum": "downloaded_images\\Chaga Full Spectrum.png",
#     "Choline 275mg": "downloaded_images\\Choline 275mg.png",
#     "Chromium Nicotinate Glycinate 200": "downloaded_images\\Chromium Nicotinate "
#     "Glycinate 200.png",
#     "CoQ10 M.R.B. 100mg": "downloaded_images\\CoQ10 M.R.B. 100mg.png",
#     "Cold-Pro Immune Formula": "downloaded_images\\Cold-Pro Immune Formula.png",
#     "Collagen Beauty - Liquid": "downloaded_images\\Collagen Beauty - Liquid.png",
#     "Collagen Beauty - Powder": "downloaded_images\\Collagen Beauty - Powder.png",
#     "Collagen Bone - Powder": "downloaded_images\\Collagen Bone - Powder.png",
#     "Collagen Full Spectrum - Powder": "downloaded_images\\Collagen Full Spectrum "
#     "- Powder.png",
#     "Collagen Full Spectrum Blend - Liquid": "downloaded_images\\Collagen Full "
#     "Spectrum Blend - Liquid.png",
#     "Collagen Joint & Cartilage - Powder": "downloaded_images\\Collagen Joint & "
#     "Cartilage - Powder.png",
#     "Collagen Tendo Recover - Powder": "downloaded_images\\Collagen Tendo Recover "
#     "- Powder.png",
#     "Collagen Tone - Powder (formerly Collagen Muscle Tone)": "downloaded_images\\Collagen "
#     "Tone - Powder "
#     "(formerly Collagen "
#     "Muscle Tone).png",
#     "Cordyceps Full Spectrum": "downloaded_images\\Cordyceps Full Spectrum.png",
#     "Cramp Relief": "downloaded_images\\Cramp Relief.png",
#     "Curcumin Unlocked": "downloaded_images\\Curcumin Unlocked.png",
#     "Curcumin-Pro": "downloaded_images\\Curcumin-Pro.png",
#     "D3 & K2 - Organic Coconut Oil": "downloaded_images\\D3 & K2 - Organic "
#     "Coconut Oil.png",
#     "D3 & K2 Drops - MCT base": "downloaded_images\\D3 & K2 Drops - MCT base.png",
#     "D3 - Organic Coconut Oil": "downloaded_images\\D3 - Organic Coconut Oil.png",
#     "D3 2500IU - MCT Base": "downloaded_images\\D3 2500IU - MCT Base.png",
#     "D3 Drops 1000IU - MCT base": "downloaded_images\\D3 Drops 1000IU - MCT "
#     "base.png",
#     "D3 Drops 1000IU - Vegan": "downloaded_images\\D3 Drops 1000IU - Vegan.png",
#     "D3 Drops 2500IU - MCT Base": "downloaded_images\\D3 Drops 2500IU - MCT "
#     "Base.png",
#     "D3 Drops Kids 400IU - MCT base": "downloaded_images\\D3 Drops Kids 400IU - "
#     "MCT base.png",
#     "Detox-Pro Formula": "downloaded_images\\Detox-Pro Formula.png",
#     "Digestive Enzymes": "downloaded_images\\Digestive Enzymes.png",
#     "Elderberry C Chewable - Berry Burst": "downloaded_images\\Elderberry C "
#     "Chewable - Berry Burst.png",
#     "Elderberry C Liquid - Berry Burst": "downloaded_images\\Elderberry C Liquid "
#     "- Berry Burst.png",
#     "ElectroMag Effervescent Drink - Box": "downloaded_images\\ElectroMag "
#     "Effervescent Drink - Box.png",
#     "EliteNeuro": "downloaded_images\\EliteNeuro.png",
#     "Eye-Pro Formula": "downloaded_images\\Eye-Pro Formula.png",
#     "Fibre Feel": "downloaded_images\\Fibre Feel.png",
#     "GABA 500": "downloaded_images\\GABA 500.png",
#     "GI-Pro Formula (formerly Digestion & IBS)": "downloaded_images\\GI-Pro "
#     "Formula (formerly Digestion & "
#     "IBS).png",
#     "Green Tea": "downloaded_images\\Green Tea.png",
#     "Green Up! with GRAMS": "downloaded_images\\Green Up! with GRAMS.png",
#     "Gut Repair": "downloaded_images\\Gut Repair.png",
#     "Healthy Bones MCHA": "downloaded_images\\Healthy Bones MCHA.png",
#     "Healthy Bones Vegan": "downloaded_images\\Healthy Bones Vegan.png",
#     "Healthy Hair": "downloaded_images\\Healthy Hair.png",
#     "Healthy Heart": "downloaded_images\\Healthy Heart.png",
#     "Healthy Hormones": "downloaded_images\\Healthy Hormones.png",
#     "Healthy Lungs": "downloaded_images\\Healthy Lungs.png",
#     "Healthy Mood": "downloaded_images\\Healthy Mood.png",
#     "Heme Iron": "downloaded_images\\Heme Iron.png",
#     "Hya Love - Hyaluronate for Hydration": "downloaded_images\\Hya Love - "
#     "Hyaluronate for Hydration.png",
#     "I-3-C 200": "downloaded_images\\I-3-C 200.png",
#     "Immuno Berry": "downloaded_images\\Immuno Berry.png",
#     "Immuno Multi": "downloaded_images\\Immuno Multi.png",
#     "Inno-Cal-Mag Advanced": "downloaded_images\\Inno-Cal-Mag Advanced.png",
#     "Inno-Q-Nol® 100mg": "downloaded_images\\Inno-Q-Nol® 100mg.png",
#     "Inno-Q-Nol® 200mg": "downloaded_images\\Inno-Q-Nol® 200mg.png",
#     "Iron Bis·Glycinate 20": "downloaded_images\\Iron Bis·Glycinate 20.png",
#     "Iron Bis·Glycinate 20 - Liquid": "downloaded_images\\Iron Bis·Glycinate 20 - "
#     "Liquid.png",
#     "Iron Bis·Glycinate 25": "downloaded_images\\Iron Bis·Glycinate 25.png",
#     "Joint-Pro Concentrate - Liquid": "downloaded_images\\Joint-Pro Concentrate - "
#     "Liquid.png",
#     "Joint-Pro Formula": "downloaded_images\\Joint-Pro Formula.png",
#     "Joint-Pro NEM": "downloaded_images\\Joint-Pro NEM.png",
#     "K2": "downloaded_images\\K2.png",
#     "K2 Drops": "downloaded_images\\K2 Drops.png",
#     "Krill Oil": "downloaded_images\\Krill Oil.png",
#     "L-Arginine Vegan Amino Acid": "downloaded_images\\L-Arginine Vegan Amino "
#     "Acid.png",
#     "L-Glutamine Vegan Amino Acid": "downloaded_images\\L-Glutamine Vegan Amino "
#     "Acid.png",
#     "L-Glycine Vegan Amino Acid": "downloaded_images\\L-Glycine Vegan Amino "
#     "Acid.png",
#     "L-Lysine Vegan Amino Acid": "downloaded_images\\L-Lysine Vegan Amino " "Acid.png",
#     "L-Taurine Vegan Amino Acid": "downloaded_images\\L-Taurine Vegan Amino "
#     "Acid.png",
#     "L-Theanine with Magnesium": "downloaded_images\\L-Theanine with " "Magnesium.png",
#     "L-Tyrosine Vegan Amino Acid": "downloaded_images\\L-Tyrosine Vegan Amino "
#     "Acid.png",
#     "Lion's Mane Full Spectrum": "downloaded_images\\Lion's Mane Full " "Spectrum.png",
#     "Liposomal Coenzyme Q10 75mg - Citrus": "downloaded_images\\Liposomal "
#     "Coenzyme Q10 75mg - Citrus.png",
#     "Liposomal Curcumin 100 - Peach": "downloaded_images\\Liposomal Curcumin 100 "
#     "- Peach.png",
#     "Liposomal GABA - Citrus": "downloaded_images\\Liposomal GABA - Citrus.png",
#     "Liposomal Glutathione": "downloaded_images\\Liposomal Glutathione.png",
#     "Liposomal Magnesium - Nutty Chocolate Caramel": "downloaded_images\\Liposomal Magnesium - Nutty Chocolate Caramel.png",
#     "Liposomal Melatonin - Nutty Chocolate": "downloaded_images\\Liposomal Melatonin - Nutty Chocolate.png",
#     "Liposomal Milk Thistle - Coconut Caramel Nut": "downloaded_images\\Liposomal Milk Thistle - Coconut Caramel Nut.png",
#     "Liposomal NAC - Strawberry": "downloaded_images\\Liposomal NAC - Strawberry.png",
#     "Liposomal Quercetin - Pineapple": "downloaded_images\\Liposomal Quercetin - Pineapple.png",
#     "Liposomal Vitamin C - Citrus Vanilla": "downloaded_images\\Liposomal Vitamin C - Citrus Vanilla.png",
#     "Liposomal Vitamin C 1000 - Citrus Vanilla": "downloaded_images\\Liposomal Vitamin C 1000 - Citrus Vanilla.png",
#     "Lutein 20  - Blue Light Defence": "downloaded_images\\Lutein 20  - Blue Light Defence.png",
#     "Magnesium + Vegan D3 & K2": "downloaded_images\\Magnesium + Vegan D3 & " "K2.png",
#     "Magnesium Bis·Glycinate 140 Extra Gentle": "downloaded_images\\Magnesium Bis·Glycinate 140 Extra Gentle.png",
#     "Magnesium Bis·Glycinate 200 Gentle": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 200 Gentle.png",
#     "Magnesium Bis·Glycinate 200 Gentle Powder": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 200 Gentle "
#     "Powder.png",
#     "Magnesium Bis·Glycinate 300 Ultra Gentle - Juicy Blueberry": "downloaded_images\\Magnesium "
#     "Bis·Glycinate "
#     "300 Ultra "
#     "Gentle - Juicy "
#     "Blueberry.png",
#     "Magnesium Bis·Glycinate 300 Ultra Gentle - Liquid": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 300 Ultra "
#     "Gentle - Liquid.png",
#     "Magnesium Bis·Glycinate 400 Ultra Gentle - Powder": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 400 Ultra "
#     "Gentle - Powder.png",
#     "Magnesium Bis·Glycinate 50 Chewable - Tropical Pineapple": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 50 "
#     "Chewable - "
#     "Tropical "
#     "Pineapple.png",
#     "Magnesium Bis·Glycinate 80 Ultra Gentle": "downloaded_images\\Magnesium "
#     "Bis·Glycinate 80 Ultra Gentle.png",
#     "Magnesium Bis·Glycinate Drink Mix - Juicy Blueberry": "downloaded_images\\Magnesium "
#     "Bis·Glycinate Drink "
#     "Mix - Juicy "
#     "Blueberry.png",
#     "Magnesium Bis·Glycinate Drink Mix - Refreshing Orange Zest": "downloaded_images\\Magnesium "
#     "Bis·Glycinate "
#     "Drink Mix - "
#     "Refreshing "
#     "Orange "
#     "Zest.png",
#     "Magnesium Cardio + Taurine, B6 & Zinc": "downloaded_images\\Magnesium Cardio "
#     "+ Taurine, B6 & Zinc.png",
#     "Magnesium Citrate+": "downloaded_images\\Magnesium Citrate+.png",
#     "Magnesium Full Spectrum": "downloaded_images\\Magnesium Full Spectrum.png",
#     "Magnesium Malate": "downloaded_images\\Magnesium Malate.png",
#     "Magnesium Multi Mineral": "downloaded_images\\Magnesium Multi Mineral.png",
#     "Magnesium Sleep + GABA & Melatonin": "downloaded_images\\Magnesium Sleep + GABA & Melatonin.png",
#     "Magnesium Stress Release": "downloaded_images\\Magnesium Stress Release.png",
#     "Magnesium Threonate": "downloaded_images\\Magnesium Threonate.png",
#     "Melatonin 3mg Sustained-Release": "downloaded_images\\Melatonin 3mg Sustained-Release.png",
#     "Meno Chill": "downloaded_images\\Meno Chill.png",
#     "Mind-Pro Formula": "downloaded_images\\Mind-Pro Formula.png",
#     "Multi-Mushroom Full Spectrum": "downloaded_images\\Multi-Mushroom Full Spectrum.png",
#     "MuscleRescue - Fruit Punch": "downloaded_images\\MuscleRescue - Fruit Punch.png",
#     "MuscleRescue - Pineapple Punch": "downloaded_images\\MuscleRescue - Pineapple Punch.png",
#     "Myco10 Immunomodulating Mushroom Complex": "downloaded_images\\Myco10 Immunomodulating Mushroom Complex.png",
#     "Myo-Inositol": "downloaded_images\\Myo-Inositol.png",
#     "NAC+ N-Acetyl-L-Cysteine": "downloaded_images\\NAC+ N-Acetyl-L-Cysteine.png",
#     "Nattokinase": "downloaded_images\\Nattokinase.png",
#     "Olive Leaf Extract": "downloaded_images\\Olive Leaf Extract.png",
#     "Omega Twist - Peachy Mango": "downloaded_images\\Omega Twist - Peachy Mango.png",
#     "Omega Twist - Tangerine Tang": "downloaded_images\\Omega Twist - Tangerine Tang.png",
#     "Omega-Pro High DHA": "downloaded_images\\Omega-Pro High DHA.png",
#     "Omega-Pro High EPA": "downloaded_images\\Omega-Pro High EPA.png",
#     "Oregano Oil": "downloaded_images\\Oregano Oil.png",
#     "Osteo Prolong": "downloaded_images\\Osteo Prolong.png",
#     "PCOS-Pro Ultra Relief": "downloaded_images\\PCOS-Pro Ultra Relief.png",
#     "Pain-Pro Formula": "downloaded_images\\Pain-Pro Formula.png",
#     "Post-Biotik Immunobiotics": "downloaded_images\\Post-Biotik Immunobiotics.png",
#     "Prime Virility Fertility & Testosterone": "downloaded_images\\Prime Virility Fertility & Testosterone.png",
#     "Pro-Biotik 15B": "downloaded_images\\Pro-Biotik 15B.png",
#     "Pro-Biotik 50B Extra Strength": "downloaded_images\\Pro-Biotik 50B Extra Strength.png",
#     "Pro-Biotik IBS Support": "downloaded_images\\Pro-Biotik IBS Support.png",
#     "Prostate-Pro + Maca Support": "downloaded_images\\Prostate-Pro + Maca Support.png",
#     "Pureway C 600mg": "downloaded_images\\Pureway C 600mg.png",
#     "Quercetin 500mg": "downloaded_images\\Quercetin 500mg.png",
#     "Red Yeast Rice Complex": "downloaded_images\\Red Yeast Rice Complex.png",
#     "Reishi Full Spectrum": "downloaded_images\\Reishi Full Spectrum.png",
#     "Resvera-Pro": "downloaded_images\\Resvera-Pro.png",
#     "Rocket T Testosterone Recharge": "downloaded_images\\Rocket T Testosterone Recharge.png",
#     "Selenium Glycinate 200": "downloaded_images\\Selenium Glycinate 200.png",
#     "Silicon + Biotin": "downloaded_images\\Silicon + Biotin.png",
#     "Silicon + Biotin Liquid": "downloaded_images\\Silicon + Biotin Liquid.png",
#     "Sleep-Reset Melatonin": "downloaded_images\\Sleep-Reset Melatonin.png",
#     "Sleep-Restore Ashwagandha": "downloaded_images\\Sleep-Restore " "Ashwagandha.png",
#     "Synergy B": "downloaded_images\\Synergy B.png",
#     "Synergy C": "downloaded_images\\Synergy C.png",
#     "TUDCA": "downloaded_images\\TUDCA.png",
#     "Thyroid Plus": "downloaded_images\\Thyroid Plus.png",
#     "Thyroid-Pro Formula": "downloaded_images\\Thyroid-Pro Formula.png",
#     "Turkey Tail Full Spectrum": "downloaded_images\\Turkey Tail Full " "Spectrum.png",
#     "Type II Collagen": "downloaded_images\\Type II Collagen.png",
#     "UTI Protect": "downloaded_images\\UTI Protect.png",
#     "UV Skin Protect": "downloaded_images\\UV Skin Protect.png",
#     "Ubiquinol 100 with MCT Oil": "downloaded_images\\Ubiquinol 100 with MCT Oil.png",
#     "V Biotik Vaginal & UTI": "downloaded_images\\V Biotik Vaginal & UTI.png",
#     "Vitamin A - Drops": "downloaded_images\\Vitamin A - Drops.png",
#     "Vitamin C 1000mg": "downloaded_images\\Vitamin C 1000mg.png",
#     "Women's Multi": "downloaded_images\\Women's Multi.png",
#     "Zinc 50 Ultra Immune + Vitamin C": "downloaded_images\\Zinc 50 Ultra Immune + Vitamin C.png",
#     "Zinc Bis·Glycinate 25": "downloaded_images\\Zinc Bis·Glycinate 25.png",
#     "Zinc Bis·Glycinate 50 Ultra Strength": "downloaded_images\\Zinc Bis·Glycinate 50 Ultra Strength.png",
# }

import os

product_images = {
    "5-HTP 100 with B6 & Magnesium": os.path.join("downloaded_images", "5-HTP 100 with B6 & Magnesium.png"),
    "Active Multi Drink Mix - Juicy Blueberry": os.path.join("downloaded_images", "Active Multi Drink Mix - Juicy Blueberry.png"),
    "Adrenal Chill": os.path.join("downloaded_images", "Adrenal Chill.png"),
    "Adrenal Chill - Men": os.path.join("downloaded_images", "Adrenal Chill - Men.png"),
    "Adrenal-Pro Recharge Yourself": os.path.join("downloaded_images", "Adrenal-Pro Recharge Yourself.png"),
    "Adult Multi": os.path.join("downloaded_images", "Adult Multi.png"),
    "Alpha Lipoic Acid 600": os.path.join("downloaded_images", "Alpha Lipoic Acid 600.png"),
    "Antioxidant Network": os.path.join("downloaded_images", "Antioxidant Network.png"),
    "Ashwagandha Body & Mind": os.path.join("downloaded_images", "Ashwagandha Body & Mind.png"),
    "B12 Methyl 500mcg Drops": os.path.join("downloaded_images", "B12 Methyl 500mcg Drops.png"),
    "B9 Folate 200mcg Drops": os.path.join("downloaded_images", "B9 Folate 200mcg Drops.png"),
    "Beautiful Skin": os.path.join("downloaded_images", "Beautiful Skin.png"),
    "Berberine 500mg": os.path.join("downloaded_images", "Berberine 500mg.png"),
    "BioActive B": os.path.join("downloaded_images", "BioActive B.png"),
    "BioActive B - Liquid": os.path.join("downloaded_images", "BioActive B - Liquid.png"),
    "BioPQQ®": os.path.join("downloaded_images", "BioPQQ®.png"),
    "Black Walnut Complex": os.path.join("downloaded_images", "Black Walnut Complex.png"),
    "Blood Sugar Support": os.path.join("downloaded_images", "Blood Sugar Support.png"),
    "Calcium Malate Bis·Glycinate 200": os.path.join("downloaded_images", "Calcium Malate Bis·Glycinate 200.png"),
    "Chaga Full Spectrum": os.path.join("downloaded_images", "Chaga Full Spectrum.png"),
    "Choline 275mg": os.path.join("downloaded_images", "Choline 275mg.png"),
    "Chromium Nicotinate Glycinate 200": os.path.join("downloaded_images", "Chromium Nicotinate Glycinate 200.png"),
    "CoQ10 M.R.B. 100mg": os.path.join("downloaded_images", "CoQ10 M.R.B. 100mg.png"),
    "Cold-Pro Immune Formula": os.path.join("downloaded_images", "Cold-Pro Immune Formula.png"),
    "Collagen Beauty - Liquid": os.path.join("downloaded_images", "Collagen Beauty - Liquid.png"),
    "Collagen Beauty - Powder": os.path.join("downloaded_images", "Collagen Beauty - Powder.png"),
    "Collagen Bone - Powder": os.path.join("downloaded_images", "Collagen Bone - Powder.png"),
    "Collagen Full Spectrum - Powder": os.path.join("downloaded_images", "Collagen Full Spectrum - Powder.png"),
    "Collagen Full Spectrum Blend - Liquid": os.path.join("downloaded_images", "Collagen Full Spectrum Blend - Liquid.png"),
    "Collagen Joint & Cartilage - Powder": os.path.join("downloaded_images", "Collagen Joint & Cartilage - Powder.png"),
    "Collagen Tendo Recover - Powder": os.path.join("downloaded_images", "Collagen Tendo Recover - Powder.png"),
    "Collagen Tone - Powder (formerly Collagen Muscle Tone)": os.path.join("downloaded_images", "Collagen Tone - Powder (formerly Collagen Muscle Tone).png"),
    "Cordyceps Full Spectrum": os.path.join("downloaded_images", "Cordyceps Full Spectrum.png"),
    "Cramp Relief": os.path.join("downloaded_images", "Cramp Relief.png"),
    "Curcumin Unlocked": os.path.join("downloaded_images", "Curcumin Unlocked.png"),
    "Curcumin-Pro": os.path.join("downloaded_images", "Curcumin-Pro.png"),
    "D3 & K2 - Organic Coconut Oil": os.path.join("downloaded_images", "D3 & K2 - Organic Coconut Oil.png"),
    "D3 & K2 Drops - MCT base": os.path.join("downloaded_images", "D3 & K2 Drops - MCT base.png"),
    "D3 - Organic Coconut Oil": os.path.join("downloaded_images", "D3 - Organic Coconut Oil.png"),
    "D3 2500IU - MCT Base": os.path.join("downloaded_images", "D3 2500IU - MCT Base.png"),
    "D3 Drops 1000IU - MCT base": os.path.join("downloaded_images", "D3 Drops 1000IU - MCT base.png"),
    "D3 Drops 1000IU - Vegan": os.path.join("downloaded_images", "D3 Drops 1000IU - Vegan.png"),
    "D3 Drops 2500IU - MCT Base": os.path.join("downloaded_images", "D3 Drops 2500IU - MCT Base.png"),
    "D3 Drops Kids 400IU - MCT base": os.path.join("downloaded_images", "D3 Drops Kids 400IU - MCT base.png"),
    "Detox-Pro Formula": os.path.join("downloaded_images", "Detox-Pro Formula.png"),
    "Digestive Enzymes": os.path.join("downloaded_images", "Digestive Enzymes.png"),
    "Elderberry C Chewable - Berry Burst": os.path.join("downloaded_images", "Elderberry C Chewable - Berry Burst.png"),
    "Elderberry C Liquid - Berry Burst": os.path.join("downloaded_images", "Elderberry C Liquid - Berry Burst.png"),
    "ElectroMag Effervescent Drink - Box": os.path.join("downloaded_images", "ElectroMag Effervescent Drink - Box.png"),
    "EliteNeuro": os.path.join("downloaded_images", "EliteNeuro.png"),
    "Eye-Pro Formula": os.path.join("downloaded_images", "Eye-Pro Formula.png"),
    "Fibre Feel": os.path.join("downloaded_images", "Fibre Feel.png"),
    "GABA 500": os.path.join("downloaded_images", "GABA 500.png"),
    "GI-Pro Formula (formerly Digestion & IBS)": os.path.join("downloaded_images", "GI-Pro Formula (formerly Digestion & IBS).png"),
    "Green Tea": os.path.join("downloaded_images", "Green Tea.png"),
    "Green Up! with GRAMS": os.path.join("downloaded_images", "Green Up! with GRAMS.png"),
    "Gut Repair": os.path.join("downloaded_images", "Gut Repair.png"),
    "Healthy Bones MCHA": os.path.join("downloaded_images", "Healthy Bones MCHA.png"),
    "Healthy Bones Vegan": os.path.join("downloaded_images", "Healthy Bones Vegan.png"),
    "Healthy Hair": os.path.join("downloaded_images", "Healthy Hair.png"),
    "Healthy Heart": os.path.join("downloaded_images", "Healthy Heart.png"),
    "Healthy Hormones": os.path.join("downloaded_images", "Healthy Hormones.png"),
    "Healthy Lungs": os.path.join("downloaded_images", "Healthy Lungs.png"),
    "Healthy Mood": os.path.join("downloaded_images", "Healthy Mood.png"),
    "Heme Iron": os.path.join("downloaded_images", "Heme Iron.png"),
    "Hya Love - Hyaluronate for Hydration": os.path.join("downloaded_images", "Hya Love - Hyaluronate for Hydration.png"),
    "I-3-C 200": os.path.join("downloaded_images", "I-3-C 200.png"),
    "Immuno Berry": os.path.join("downloaded_images", "Immuno Berry.png"),
    "Immuno Multi": os.path.join("downloaded_images", "Immuno Multi.png"),
    "Inno-Cal-Mag Advanced": os.path.join("downloaded_images", "Inno-Cal-Mag Advanced.png"),
    "Inno-Q-Nol® 100mg": os.path.join("downloaded_images", "Inno-Q-Nol® 100mg.png"),
    "Inno-Q-Nol® 200mg": os.path.join("downloaded_images", "Inno-Q-Nol® 200mg.png"),
    "Iron Bis·Glycinate 20": os.path.join("downloaded_images", "Iron Bis·Glycinate 20.png"),
    "Iron Bis·Glycinate 20 - Liquid": os.path.join("downloaded_images", "Iron Bis·Glycinate 20 - Liquid.png"),
    "Iron Bis·Glycinate 25": os.path.join("downloaded_images", "Iron Bis·Glycinate 25.png"),
    "Joint-Pro Concentrate - Liquid": os.path.join("downloaded_images", "Joint-Pro Concentrate - Liquid.png"),
    "Joint-Pro Formula": os.path.join("downloaded_images", "Joint-Pro Formula.png"),
    "Joint-Pro NEM": os.path.join("downloaded_images", "Joint-Pro NEM.png"),
    "K2": os.path.join("downloaded_images", "K2.png"),
    "K2 Drops": os.path.join("downloaded_images", "K2 Drops.png"),
    "Krill Oil": os.path.join("downloaded_images", "Krill Oil.png"),
    "L-Arginine Vegan Amino Acid": os.path.join("downloaded_images", "L-Arginine Vegan Amino Acid.png"),
    "L-Glutamine Vegan Amino Acid": os.path.join("downloaded_images", "L-Glutamine Vegan Amino Acid.png"),
    "L-Glycine Vegan Amino Acid": os.path.join("downloaded_images", "L-Glycine Vegan Amino Acid.png"),
    "L-Lysine Vegan Amino Acid": os.path.join("downloaded_images", "L-Lysine Vegan Amino Acid.png"),
    "L-Taurine Vegan Amino Acid": os.path.join("downloaded_images", "L-Taurine Vegan Amino Acid.png"),
    "L-Theanine with Magnesium": os.path.join("downloaded_images", "L-Theanine with Magnesium.png"),
    "L-Tyrosine Vegan Amino Acid": os.path.join("downloaded_images", "L-Tyrosine Vegan Amino Acid.png"),
    "Lion's Mane Full Spectrum": os.path.join("downloaded_images", "Lion's Mane Full Spectrum.png"),
    "Liposomal Coenzyme Q10 75mg - Citrus": os.path.join("downloaded_images", "Liposomal Coenzyme Q10 75mg - Citrus.png"),
    "Liposomal Curcumin 100 - Peach": os.path.join("downloaded_images", "Liposomal Curcumin 100 - Peach.png"),
    "Liposomal GABA - Citrus": os.path.join("downloaded_images", "Liposomal GABA - Citrus.png"),
    "Liposomal Glutathione": os.path.join("downloaded_images", "Liposomal Glutathione.png"),
    "Liposomal Magnesium - Nutty Chocolate Caramel": os.path.join("downloaded_images", "Liposomal Magnesium - Nutty Chocolate Caramel.png"),
    "Liposomal Melatonin - Nutty Chocolate": os.path.join("downloaded_images", "Liposomal Melatonin - Nutty Chocolate.png"),
    "Liposomal Milk Thistle - Coconut Caramel Nut": os.path.join("downloaded_images", "Liposomal Milk Thistle - Coconut Caramel Nut.png"),
    "Liposomal NAC - Strawberry": os.path.join("downloaded_images", "Liposomal NAC - Strawberry.png"),
    "Liposomal Quercetin - Pineapple": os.path.join("downloaded_images", "Liposomal Quercetin - Pineapple.png"),
    "Liposomal Vitamin C - Citrus Vanilla": os.path.join("downloaded_images", "Liposomal Vitamin C - Citrus Vanilla.png"),
    "Liposomal Vitamin C 1000 - Citrus Vanilla": os.path.join("downloaded_images", "Liposomal Vitamin C 1000 - Citrus Vanilla.png"),
    "Lutein 20  - Blue Light Defence": os.path.join("downloaded_images", "Lutein 20  - Blue Light Defence.png"),
    "Magnesium + Vegan D3 & K2": os.path.join("downloaded_images", "Magnesium + Vegan D3 & K2.png"),
    "Magnesium Bis·Glycinate 140 Extra Gentle": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 140 Extra Gentle.png"),
    "Magnesium Bis·Glycinate 200 Gentle": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 200 Gentle.png"),
    "Magnesium Bis·Glycinate 200 Gentle Powder": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 200 Gentle Powder.png"),
    "Magnesium Bis·Glycinate 300 Ultra Gentle - Juicy Blueberry": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 300 Ultra Gentle - Juicy Blueberry.png"),
    "Magnesium Bis·Glycinate 300 Ultra Gentle - Liquid": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 300 Ultra Gentle - Liquid.png"),
    "Magnesium Bis·Glycinate 400 Ultra Gentle - Powder": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 400 Ultra Gentle - Powder.png"),
    "Magnesium Bis·Glycinate 50 Chewable - Tropical Pineapple": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 50 Chewable - Tropical Pineapple.png"),
    "Magnesium Bis·Glycinate 80 Ultra Gentle": os.path.join("downloaded_images", "Magnesium Bis·Glycinate 80 Ultra Gentle.png"),
    "Magnesium Bis·Glycinate Drink Mix - Juicy Blueberry": os.path.join("downloaded_images", "Magnesium Bis·Glycinate Drink Mix - Juicy Blueberry.png"),
    "Magnesium Bis·Glycinate Drink Mix - Refreshing Orange Zest": os.path.join("downloaded_images", "Magnesium Bis·Glycinate Drink Mix - Refreshing Orange Zest.png"),
    "Magnesium Cardio + Taurine, B6 & Zinc": os.path.join("downloaded_images", "Magnesium Cardio + Taurine, B6 & Zinc.png"),
    "Magnesium Citrate+": os.path.join("downloaded_images", "Magnesium Citrate+.png"),
    "Magnesium Full Spectrum": os.path.join("downloaded_images", "Magnesium Full Spectrum.png"),
    "Magnesium Malate": os.path.join("downloaded_images", "Magnesium Malate.png"),
    "Magnesium Multi Mineral": os.path.join("downloaded_images", "Magnesium Multi Mineral.png"),
    "Magnesium Sleep + GABA & Melatonin": os.path.join("downloaded_images", "Magnesium Sleep + GABA & Melatonin.png"),
    "Magnesium Stress Release": os.path.join("downloaded_images", "Magnesium Stress Release.png"),
    "Magnesium Threonate": os.path.join("downloaded_images", "Magnesium Threonate.png"),
    "Melatonin 3mg Sustained-Release": os.path.join("downloaded_images", "Melatonin 3mg Sustained-Release.png"),
    "Meno Chill": os.path.join("downloaded_images", "Meno Chill.png"),
    "Mind-Pro Formula": os.path.join("downloaded_images", "Mind-Pro Formula.png"),
    "Multi-Mushroom Full Spectrum": os.path.join("downloaded_images", "Multi-Mushroom Full Spectrum.png"),
    "MuscleRescue - Fruit Punch": os.path.join("downloaded_images", "MuscleRescue - Fruit Punch.png"),
    "MuscleRescue - Pineapple Punch": os.path.join("downloaded_images", "MuscleRescue - Pineapple Punch.png"),
    "Myco10 Immunomodulating Mushroom Complex": os.path.join("downloaded_images", "Myco10 Immunomodulating Mushroom Complex.png"),
    "Myo-Inositol": os.path.join("downloaded_images", "Myo-Inositol.png"),
    "NAC+ N-Acetyl-L-Cysteine": os.path.join("downloaded_images", "NAC+ N-Acetyl-L-Cysteine.png"),
    "Nattokinase": os.path.join("downloaded_images", "Nattokinase.png"),
    "Olive Leaf Extract": os.path.join("downloaded_images", "Olive Leaf Extract.png"),
    "Omega Twist - Peachy Mango": os.path.join("downloaded_images", "Omega Twist - Peachy Mango.png"),
    "Omega Twist - Tangerine Tang": os.path.join("downloaded_images", "Omega Twist - Tangerine Tang.png"),
    "Omega-Pro High DHA": os.path.join("downloaded_images", "Omega-Pro High DHA.png"),
    "Omega-Pro High EPA": os.path.join("downloaded_images", "Omega-Pro High EPA.png"),
    "Oregano Oil": os.path.join("downloaded_images", "Oregano Oil.png"),
    "Osteo Prolong": os.path.join("downloaded_images", "Osteo Prolong.png"),
    "PCOS-Pro Ultra Relief": os.path.join("downloaded_images", "PCOS-Pro Ultra Relief.png"),
    "Pain-Pro Formula": os.path.join("downloaded_images", "Pain-Pro Formula.png"),
    "Post-Biotik Immunobiotics": os.path.join("downloaded_images", "Post-Biotik Immunobiotics.png"),
    "Prime Virility Fertility & Testosterone": os.path.join("downloaded_images", "Prime Virility Fertility & Testosterone.png"),
    "Pro-Biotik 15B": os.path.join("downloaded_images", "Pro-Biotik 15B.png"),
    "Pro-Biotik 50B Extra Strength": os.path.join("downloaded_images", "Pro-Biotik 50B Extra Strength.png"),
    "Pro-Biotik IBS Support": os.path.join("downloaded_images", "Pro-Biotik IBS Support.png"),
    "Prostate-Pro + Maca Support": os.path.join("downloaded_images", "Prostate-Pro + Maca Support.png"),
    "Pureway C 600mg": os.path.join("downloaded_images", "Pureway C 600mg.png"),
    "Quercetin 500mg": os.path.join("downloaded_images", "Quercetin 500mg.png"),
    "Red Yeast Rice Complex": os.path.join("downloaded_images", "Red Yeast Rice Complex.png"),
    "Reishi Full Spectrum": os.path.join("downloaded_images", "Reishi Full Spectrum.png"),
    "Resvera-Pro": os.path.join("downloaded_images", "Resvera-Pro.png"),
    "Rocket T Testosterone Recharge": os.path.join("downloaded_images", "Rocket T Testosterone Recharge.png"),
    "Selenium Glycinate 200": os.path.join("downloaded_images", "Selenium Glycinate 200.png"),
    "Silicon + Biotin": os.path.join("downloaded_images", "Silicon + Biotin.png"),
    "Silicon + Biotin Liquid": os.path.join("downloaded_images", "Silicon + Biotin Liquid.png"),
    "Sleep-Reset Melatonin": os.path.join("downloaded_images", "Sleep-Reset Melatonin.png"),
    "Sleep-Restore Ashwagandha": os.path.join("downloaded_images", "Sleep-Restore Ashwagandha.png"),
    "Synergy B": os.path.join("downloaded_images", "Synergy B.png"),
    "Synergy C": os.path.join("downloaded_images", "Synergy C.png"),
    "TUDCA": os.path.join("downloaded_images", "TUDCA.png"),
    "Thyroid Plus": os.path.join("downloaded_images", "Thyroid Plus.png"),
    "Thyroid-Pro Formula": os.path.join("downloaded_images", "Thyroid-Pro Formula.png"),
    "Turkey Tail Full Spectrum": os.path.join("downloaded_images", "Turkey Tail Full Spectrum.png"),
    "Type II Collagen": os.path.join("downloaded_images", "Type II Collagen.png"),
    "UTI Protect": os.path.join("downloaded_images", "UTI Protect.png"),
    "UV Skin Protect": os.path.join("downloaded_images", "UV Skin Protect.png"),
    "Ubiquinol 100 with MCT Oil": os.path.join("downloaded_images", "Ubiquinol 100 with MCT Oil.png"),
    "V Biotik Vaginal & UTI": os.path.join("downloaded_images", "V Biotik Vaginal & UTI.png"),
    "Vitamin A - Drops": os.path.join("downloaded_images", "Vitamin A - Drops.png"),
    "Vitamin C 1000mg": os.path.join("downloaded_images", "Vitamin C 1000mg.png"),
    "Women's Multi": os.path.join("downloaded_images", "Women's Multi.png"),
    "Zinc 50 Ultra Immune + Vitamin C": os.path.join("downloaded_images", "Zinc 50 Ultra Immune + Vitamin C.png"),
    "Zinc Bis·Glycinate 25": os.path.join("downloaded_images", "Zinc Bis·Glycinate 25.png"),
    "Zinc Bis·Glycinate 50 Ultra Strength": os.path.join("downloaded_images", "Zinc Bis·Glycinate 50 Ultra Strength.png"),
}

